### ISSUE TITLE
Broken link to Introduction to command line course

### ISSUE THREAD

**Issue by jcwomack** [ACRC/HPC-community-docs#18]
The link to @alleetanner's Introduction to the command line in the Abaqus documentation is broken, and needs updating to <https://alleetanner.github.io/intro_to_CLI/>.

https://github.com/ACRC/HPC-community-docs/blob/5c98f8177ce6ae2a48224c28a21991f810aac1a1/source/engineering/abaqus/index.md?plain=1#L18

**Comment by jcwomack** [comment]
The link may need further changes. There are two plausible links: <https://alleetanner.github.io/intro_to_CLI/> or <https://alleetanner.github.io/intro-to-command-line/>, each of which appears to refer to a different version of the course.

**Comment by milliams** [comment]
I believe that the https://alleetanner.github.io/intro-to-command-line/ is the current version.

**Comment by jcwomack** [comment]
Fixed in PR #19
